apiVersion: apps/v1
kind: Deployment
metadata:
  name: docutok-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docutok-backend
  template:
    metadata:
      labels:
        app: docutok-backend
    spec:
      containers:
      - name: backend
        image: 932380677908.dkr.ecr.us-west-2.amazonaws.com/docutok-backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: docutok-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docutok-secrets
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql+asyncpg://docutok:$(POSTGRES_PASSWORD)@docutok-db-postgresql.default.svc.cluster.local:5432/docutok"
        # Add necessary mounts for uploads if not using S3
