apiVersion: apps/v1
kind: Deployment
metadata:
  name: docutok-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docutok-frontend
  template:
    metadata:
      labels:
        app: docutok-frontend
    spec:
      containers:
      - name: frontend
        image: 932380677908.dkr.ecr.us-west-2.amazonaws.com/docutok-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "/api" # Handled by Ingress rewrite usually, or public LB URL
