apiVersion: v1
kind: Secret
metadata:
  name: docutok-secrets
type: Opaque
data:
  # Examples (ensure these are base64 encoded!)
  # Run: echo -n "value" | base64
  POSTGRES_PASSWORD: SEpBU2hoZjQ1RFVZSVQm
  SECRET_KEY: ZzdrTnVCOTNmV0EtVDgtdWdOU2F6YjFIZTJ4amdhRXpVVGVnT1FSSGxLVQ==
  ADMIN_PASSWORD: SHlzdFNCNmZFMyZeaHFwTQ==
