apiVersion: apps/v1
kind: Deployment
metadata:
  name: docutok-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docutok-worker
  template:
    metadata:
      labels:
        app: docutok-worker
    spec:
      containers:
      - name: worker
        image: 932380677908.dkr.ecr.us-west-2.amazonaws.com/docutok-backend:v32
        command: ["/bin/bash", "-c", "apt-get update && apt-get install -y ffmpeg && /app/.venv/bin/celery -A app.core.celery_app worker --loglevel=info"]
        envFrom:
        - configMapRef:
            name: docutok-config
        - secretRef:
            name: docutok-secrets
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docutok-secrets
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql+asyncpg://docutok:$(POSTGRES_PASSWORD)@docutok-db-postgresql.default.svc.cluster.local:5432/docutok"
        - name: POSTGRES_HOST
          value: "docutok-db-postgresql.default.svc.cluster.local"
        - name: POSTGRES_USER
          value: "docutok"
        - name: POSTGRES_DB
          value: "docutok"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docutok-redis
              key: redis-password
        volumeMounts:
        - name: app-core-config
          mountPath: /app/app/core/config.py
          subPath: config.py
      volumes:
      - name: app-core-config
        configMap:
          name: docutok-app-core-config
