"""Add UUID to media and links

Revision ID: 7a3b629dfbd1
Revises: 9d7b174bf18c
Create Date: 2026-02-03 01:16:20.356509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3b629dfbd1'
down_revision: Union[str, Sequence[str], None] = '9d7b174bf18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable
    op.add_column('project_links', sa.Column('uuid', sa.UUID(), nullable=True))
    op.add_column('project_media', sa.Column('uuid', sa.UUID(), nullable=True))

    # 2. Backfill existing rows with random UUIDs
    # Try gen_random_uuid() (PG 13+) or uuid_generate_v4() (uuid-ossp)
    # Using gen_random_uuid() as it is standard in modern PG
    op.execute("UPDATE project_links SET uuid = gen_random_uuid() WHERE uuid IS NULL")
    op.execute("UPDATE project_media SET uuid = gen_random_uuid() WHERE uuid IS NULL")

    # 3. Alter columns to be non-nullable
    op.alter_column('project_links', 'uuid', nullable=False)
    op.alter_column('project_media', 'uuid', nullable=False)

    # 4. Create indexes
    op.create_index(op.f('ix_project_links_uuid'), 'project_links', ['uuid'], unique=True)
    op.create_index(op.f('ix_project_media_uuid'), 'project_media', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_media_uuid'), table_name='project_media')
    op.drop_column('project_media', 'uuid')
    op.drop_index(op.f('ix_project_links_uuid'), table_name='project_links')
    op.drop_column('project_links', 'uuid')
    # ### end Alembic commands ###
