"""Add new user fields

Revision ID: 9a93e40a759e
Revises: b7b129989d2f
Create Date: 2026-02-10 23:18:04.716107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a93e40a759e'
down_revision: Union[str, Sequence[str], None] = 'b7b129989d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_ip_address', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_ip_address')
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'company')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
