"""add_show_animation_to_projects

Revision ID: c4edb300d723
Revises: e59dac7a0dea
Create Date: 2026-02-01 17:23:20.262502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4edb300d723"
down_revision: Union[str, Sequence[str], None] = "e59dac7a0dea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "show_animation", sa.Boolean(), server_default=sa.true(), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "show_animation")
    # ### end Alembic commands ###
