"""add_internal_flags

Revision ID: f132c21888a2
Revises: add_avatars_001
Create Date: 2026-01-31 17:30:27.802580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f132c21888a2'
down_revision: Union[str, Sequence[str], None] = 'add_avatars_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_docutok_customer', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_customers_uuid'), 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_uuid'), table_name='customers')
    op.create_index(op.f('ix_customers_uuid'), 'customers', ['uuid'], unique=True)
    op.drop_constraint(op.f('uq_faqs_uuid'), 'faqs', type_='unique')
    op.drop_index(op.f('ix_faqs_uuid'), table_name='faqs')
    op.create_index(op.f('ix_faqs_uuid'), 'faqs', ['uuid'], unique=True)
    op.add_column('projects', sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_projects_subdomain'), table_name='projects')
    op.drop_constraint(op.f('uq_projects_uuid'), 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_uuid'), table_name='projects')
    op.create_index(op.f('ix_projects_uuid'), 'projects', ['uuid'], unique=True)
    op.drop_column('projects', 'subdomain')
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_users_uuid'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('uq_users_uuid'), 'users', ['uuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('projects', sa.Column('subdomain', sa.VARCHAR(length=63), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_projects_uuid'), table_name='projects')
    op.create_index(op.f('ix_projects_uuid'), 'projects', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('uq_projects_uuid'), 'projects', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_projects_subdomain'), 'projects', ['subdomain'], unique=True)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('projects', 'is_demo')
    op.drop_index(op.f('ix_faqs_uuid'), table_name='faqs')
    op.create_index(op.f('ix_faqs_uuid'), 'faqs', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('uq_faqs_uuid'), 'faqs', ['uuid'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_customers_uuid'), table_name='customers')
    op.create_index(op.f('ix_customers_uuid'), 'customers', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('uq_customers_uuid'), 'customers', ['uuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('customers', 'is_docutok_customer')
    # ### end Alembic commands ###
